from ._develop_summary_reports.validate_required_ui_component import validate_required_ui_component
from ._develop_summary_reports.validate_required_api_endpoints import validate_required_api_endpoints
from ._develop_summary_reports.create_expense_data_service import create_expense_data_service
from ._develop_summary_reports.create_analytics_engine import create_analytics_engine
from ._develop_summary_reports.generate_chart_components import generate_chart_components
from ._develop_summary_reports.design_dashboard_layout import design_dashboard_layout
from ._develop_summary_reports.implement_data_aggregation import implement_data_aggregation
from ._develop_summary_reports.implement_time_based_analytics import implement_time_based_analytics
from ._develop_summary_reports.implement_category_breakdown import implement_category_breakdown
from ._develop_summary_reports.generate_dashboard_component import generate_dashboard_component

from pydantic import BaseModel, Field
from typing import List


class DesignUiComponentsOutput(BaseModel):
    """Pydantic model for design_ui_components node outputs."""
    ui_components: List[str] = (
        Field(..., description="Names of UI components and screens derived from the functional requirements")
    )


class ImplementDataStorageOutput(BaseModel):
    """Pydantic model for implement_data_storage node outputs."""
    api_endpoints: List[str] = (
        Field(..., description="List of backend API endpoint definitions (e.g., /expenses, /users)")
    )


class DevelopSummaryReportsOutput(BaseModel):
    """Pydantic model for develop_summary_reports node outputs."""
    report_dashboard_component: str = (
        Field(..., description="Identifier or filename of the report dashboard component")
    )


def develop_summary_reports(design_ui_components_input: DesignUiComponentsOutput, implement_data_storage_input: ImplementDataStorageOutput, **kwargs) -> DevelopSummaryReportsOutput:
    """
    Generate the report dashboard component for expense summaries and
    visualizations.

    Parameters
    ----------
    ui_components : List[str]
        List of UI component names generated by the design step, must
        include a placeholder for the report dashboard screen.
    api_endpoints : List[str]
        List of backend API endpoints provided by the storage layer, used to
        fetch expense data.

    Returns
    -------
    str
        Filename or identifier of the generated report dashboard component
        (e.g., 'report_dashboard.py').

    Raises
    ------
    ValueError
        If the required UI component for the dashboard is missing from
        ui_components.
    RuntimeError
        If necessary API endpoints for expense retrieval are not present.

    Examples
    --------
    >>> create_report_dashboard(['LoginScreen', 'ReportDashboard'],
    ['/expenses', '/users'])
    'report_dashboard.py'

    >>> create_report_dashboard(['ReportDashboard'], ['/expenses'])
    'report_dashboard.py'

    """
    ui_components: List[str] = design_ui_components_input.ui_components
    api_endpoints: List[str] = implement_data_storage_input.api_endpoints
    
    validate_required_ui_component(ui_components=ui_components, required_component="ReportDashboard")
    validate_required_api_endpoints(api_endpoints=api_endpoints, required_endpoints=["/expenses"])
    
    expense_data_service: str = create_expense_data_service(api_endpoints=api_endpoints)
    analytics_engine: str = create_analytics_engine()
    chart_components: List[str] = generate_chart_components()
    
    dashboard_layout: str = design_dashboard_layout(chart_components=chart_components)
    aggregation_logic: str = implement_data_aggregation(expense_data_service=expense_data_service)
    time_analytics: str = implement_time_based_analytics(analytics_engine=analytics_engine)
    category_breakdown: str = implement_category_breakdown(analytics_engine=analytics_engine)
    
    dashboard_filename: str = generate_dashboard_component(
        layout=dashboard_layout,
        aggregation=aggregation_logic,
        time_analytics=time_analytics,
        category_breakdown=category_breakdown,
        charts=chart_components
    )
    
    return DevelopSummaryReportsOutput(report_dashboard_component=dashboard_filename)