import json


def generate_crud_handlers(orm_models: str) -> str:
    """
    Generate CRUD handler identifiers for a set of ORM models.

    Parameters
    ----------
    orm_models : str
        A JSON‑encoded string representing a dictionary where keys are model
        names (e.g., "User") and values are the ORM class identifiers (e.g.,
        "UserModel").

    Returns
    -------
    str
        A JSON‑encoded string representing a dictionary with the same keys
        as `orm_models`; each value is the autogenerated CRUD handler name
        for the corresponding model.

    Raises
    ------
    ValueError
        If `orm_models` cannot be parsed as valid JSON or does not represent
        a dictionary.
    TypeError
        If any key or value in the parsed dictionary is not a string.

    Examples
    --------
    >>> generate_crud_handlers('{"User": "UserModel", "Expense":
    "ExpenseModel"}')
    '{"User": "user_crud_handler", "Expense": "expense_crud_handler"}'

    >>> generate_crud_handlers('{"Category": "CategoryModel"}')
    '{"Category": "category_crud_handler"}'

    """
    
    try:
        parsed_models = json.loads(orm_models)
    except json.JSONDecodeError:
        raise ValueError("orm_models cannot be parsed as valid JSON")
    
    if not isinstance(parsed_models, dict):
        raise ValueError("orm_models does not represent a dictionary")
    
    for key, value in parsed_models.items():
        if not isinstance(key, str) or not isinstance(value, str):
            raise TypeError("All keys and values in the dictionary must be strings")
    
    crud_handlers = {}
    for model_name in parsed_models.keys():
        handler_name = model_name.lower() + "_crud_handler"
        crud_handlers[model_name] = handler_name
    
    return json.dumps(crud_handlers)